---
title: "TidyTuesday"
author: "Camila Vargas"
date: "May 14, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Set-Up
```{r}

library(tidyverse)
library(lubridate)
library(ggbeeswarm) #Provides two methods of plotting categorical scatter plots such that the arrangement of points within a category reflects the density of data at that region, and avoids over-plotting.

```



##TidyTuesday - May 14, 2019 - Nobel Proze data

##Read in data
```{r}
nobel <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-14/nobel_winners.csv")


nobel_winner_all_pubs <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-14/nobel_winner_all_pubs.csv")
```

```{r}
p <- 
  nobel %>% 
  mutate(age =  prize_year - year(birth_date)) %>% 
  ggplot(aes(x = category,
             y = age, ##in order to make beewarm work you need to set the y axis as the variable you want to expand; in this case age.
             colour = gender,
             alpha = gender)) +
  ggbeeswarm::geom_beeswarm() + # geom_beewarm allows to offset points within categories to reduce overplotting
  coord_flip() + #in order to plot the x-axis vertically for better visual flop the axis!
  scale_color_manual(values = c("#BB1288", "#5867A6")) +
  scale_alpha_manual(values = c(1, .4)) +
  theme_minimal() +
  labs(title = "Way Beyond Gender Imbalance",
       subtitle = "Nobel prize laureates until 2016",
       colour = "Gender",
       alpha = "Gender",
       x = "Category",
       y = "Age",
       caption = "Source: Kaggle | Plot by @othomn")

# I was wondering if with a beeswarm plot you can show also every nobel price as a point. The picture 

# some checks
nobel %>% filter(gender == "Female") %>% select(category, full_name) #%>% View()
nobel %>%
  mutate(age =  prize_year - year(birth_date)) %>% 
  filter(age < 25) %>% 
  select(category, full_name) #%>% View()


# save --------------------------------------------------------------------

png(filename = "plots/2-20-nobel-prize.png",
    res = 300,
    height = 1800,
    width = 2400)
p %>% print()
dev.off()
```



```{r}

```


